import Providers from "./Providers";
import Header from "@/components/Header.component";

import "./globals.css";

export const metadata = {
  title: "IMDb Clone",
  description: "Generated by create next app",
  content: "This is a IMDb Clone",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />

          {children}
        </Providers>
      </body>
    </html>
  );
}
