import "./globals.css";
import Header from "@/components/Header.component";

export const metadata = {
  title: "IMDb Clone",
  description: "Generated by create next app",
  content: "This is a IMDb Clone",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />

        {children}
      </body>
    </html>
  );
}
